// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using postVideo.Model;
using System;

namespace postVideo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180619163507_addUserConnectionsToDB")]
    partial class addUserConnectionsToDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("postVideo.Model.Videos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<string>("Tittle");

                    b.Property<string>("VideoDescription");

                    b.HasKey("ID");

                    b.ToTable("VideoList");
                });
#pragma warning restore 612, 618
        }
    }
}
